"""Small seed set for deterministic AI company canonicalization."""

from __future__ import annotations

SEED_ENTITIES: tuple[str, ...] = (
    "OpenAI",
    "Anthropic",
    "Google",
    "Google DeepMind",
    "Microsoft",
    "Meta",
    "Mistral AI",
    "Cohere",
    "Perplexity",
    "Hugging Face",
    "Stability AI",
    "Midjourney",
    "Runway",
    "ElevenLabs",
    "Scale AI",
    "Databricks",
    "DataRobot",
    "Adept",
    "Character.AI",
    "xAI",
    "Inflection AI",
    "Sakana AI",
    "Together AI",
    "NVIDIA",
    "Cerebras",
    "Groq",
    "Modal",
    "Replicate",
    "LangChain",
    "Pinecone",
    "Weaviate",
    "LlamaIndex",
    "Weights & Biases",
    "Writer",
    "Jasper",
    "Copy.ai",
    "Synthesia",
    "Descript",
    "Harvey",
    "Glean",
    "Hebbia",
    "Dust",
    "Anysphere",
    "Cursor",
    "Replit",
    "Lovable",
    "Abridge",
    "Tempus",
    "Insilico Medicine",
    "Wayve",
    "Figure",
    "Maven AGI",
    "Poolside",
    "DeepSeek",
    "Alibaba Cloud",
    "Pika Labs",
    "Suno AI",
    "Udio",
    "Kuaishou",
    "Black Forest Labs",
    "Ideogram",
    "Luma AI",
    "HeyGen",
    "Vercel",
    "StackBlitz",
    "Cognition",
    "Qdrant",
    "Zilliz",
    "Chroma",
    "CrewAI",
    "Ollama",
    "Baidu",
    "ByteDance",
    "Tencent",
    "Otter.ai",
    "Murf",
    "Krea",
    "Phind",
    "Photoroom",
    "You.com",
    "Zapier",
    "Roboflow",
    "Fireflies",
    "Captions Inc.",
    "Play.ht",
    "Topaz Labs",
    "InVideo",
    "Superhuman",
    "Labelbox",
    "OpusPro",
    "Make",
    "Portkey",
    "Raycast",
    "Unsloth AI",
    "Quora",
    "RunPod",
    "Significant Gravitas",
    "Luka Inc.",
    "PromptLayer",
    "Palantir",
)

