"""Small seed set for deterministic AI company canonicalization."""

from __future__ import annotations

SEED_ENTITIES: tuple[str, ...] = (
    "OpenAI",
    "Anthropic",
    "Google DeepMind",
    "Mistral AI",
    "Cohere",
    "Perplexity",
    "Hugging Face",
    "Stability AI",
    "Midjourney",
    "Runway",
    "ElevenLabs",
    "Scale AI",
    "Databricks",
    "DataRobot",
    "Adept",
    "Character.AI",
    "xAI",
    "Inflection AI",
    "Sakana AI",
    "Together AI",
    "NVIDIA",
    "Cerebras",
    "Groq",
    "Modal",
    "Replicate",
    "LangChain",
    "Pinecone",
    "Weaviate",
    "LlamaIndex",
    "Weights & Biases",
    "Writer",
    "Jasper",
    "Copy.ai",
    "Synthesia",
    "Descript",
    "Harvey",
    "Glean",
    "Hebbia",
    "Dust",
    "Anysphere",
    "Cursor",
    "Replit",
    "Lovable",
    "Abridge",
    "Tempus",
    "Insilico Medicine",
    "Wayve",
    "Figure",
    "Maven AGI",
    "Poolside",
)

